/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],

  // But you can create a sidebar manually

  HTML: [
    {
      type: 'category',
      label: 'HTML Tutorials',
      items: [
        'languages/html/introduction',
        'languages/html/html_editors',
        'languages/html/html_boilerplate',
        'languages/html/html_tags',
        'languages/html/html_attributes',
        'languages/html/html_formatting',
      ],
    },
  ],

  Python: [
    {
      type: 'category',
      label: 'Python Tutorials',
      items: [
        'languages/python/introduction',
        'languages/python/python_installation',
      ],
    },
  ],


};

module.exports = sidebars;
